### ISSUE TITLE
Tests broken

### ISSUE THREAD

**Issue by jluttine** [tbekolay/pytest-cram#7]
`pytest-cram` has worked before but after upgrading some dependencies, it doesn't pass the tests anymore. Here's the log of running `pytest pytest_cram`: https://gist.github.com/jluttine/a535e10e78b53c8eb123a78767d71120

**Comment by jluttine** [comment]
More specifically: Upgrading pytest from 3.2 to 3.3 breaks the tests.

**Comment by tbekolay** [comment]
Thanks for filing an issue! I'll look into this as soon as I can.

**Comment by jluttine** [comment]
Don't mean to put pressure but just interested if you have any estimate when you might find the time for this? I'm maintaining this package for one Linux distro and the package is now broken, that's why I'm interested. Or do you have any ideas how to work around this issue?

**Comment by tbekolay** [comment]
Oh, I had no idea this was being packaged for a Linux distro, thanks for doing that!

I figured out that the issue was the new progress indicators on pytest output (and the [console_output_style option](https://docs.pytest.org/en/latest/customize.html#confval-console_output_style)). I've pushed a commit that fixes the tests and will now make a 0.2.0 release.

**Comment by tbekolay** [comment]
I've now made the [0.2.0 release](https://pypi.python.org/pypi/pytest-cram/0.2.0). Please let me know if that's working for you.

**Comment by jluttine** [comment]
Great, thanks a lot! Now it works. And yes, I'm maintaining this package for NixOS.

**Comment by tbekolay** [comment]
Very cool :) Let me know if you run into any more issues.
