### ISSUE TITLE
pytest-cram conflicts with pytest-regtest

### ISSUE THREAD

**Issue by taschini** [tbekolay/pytest-cram#8]
The plugin [pytest-regtest](https://sissource.ethz.ch/sispub/pytest-regtest) expects all items to have `funcargs` attribute, but the pytest-cram plugin produces items that do not have it.

It would perhaps be better to have something like

class CramItem(pytest.Item, pytest.File):
```
    ...
    def __init__(self, path, parent):
         ...
         self.funcargs = {}
```

See also the [corresponding issue](https://sissource.ethz.ch/sispub/pytest-regtest/issues/1).

**Comment by tbekolay** [comment]
It looks like this has been fixed in pytest-regtest. I'm tempted to leave pytest-cram as is, because I believe usage of "funcargs" (as opposed to fixtures) is deprecated in pytest, and if `funcargs` was something that was expected of `pytest.Item` or `pytest.File` subclasses, it should be defined in the `Item` or `File` `__init__` method.

I did notice that I am not calling the superclass `__init__`s  correctly (since I inherit from both) so I added a commit to fix that (but haven't made a release, as there's no indication that it's necessary from my testing -- more of a "just in case" thing).

Please reopen if you disagree!

**Comment by taschini** [comment]
Thank you for looking into it.
